# Site settings
title: Yapeng Zheng
first_name: Yapeng
last_name: Zheng
email: yapengzheng@link.cuhk.edu.hk
description: Ph.D. Candidate in Economics at The Chinese University of Hong Kong
footer_text: Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme
keywords: economics, econometrics, CUHK
lang: en
icon: ⚡️

url: https://yapengzheng.github.io
baseurl: ""

# SEO
google_site_verification: pacN-Sv_w9Ds7dnQWN4OAfzPTRNr604vEIsfW4SkeoE

# Jekyll settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"

# Includes & excludes
include: ["_pages"]
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Plugins - minimal only
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed

# Jekyll Scholar
scholar:
  last_name: [Zheng]
  first_name: [Yapeng, Y.]
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib_template
  query: "@*"
  group_by: year
  group_order: descending
  details_dir: bibliography
  details_link: Details
  bibliography_list_tags: false

# Filtered bibtex keywords
filtered_bibtex_keywords:
  - abbr
  - abstract
  - bibtex_show
  - selected

# Sitemap
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed

# Optional features
enable_progressbar: false
enable_darkmode: false
